# Netlify configuration for Next.js deployment

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Use Next.js plugin for proper deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"
